build:
	./scripts/build.sh
bash:
	./scripts/bash.sh
start:
	./scripts/start.sh
migrate-head:
	./scripts/migrate-head.sh
attach-db:
	./scripts/attach-db.sh
coverage-tests:
	./scripts/coverage-tests.sh
format:
	./scripts/format.sh
static-tests:
	./scripts/static-tests.sh
bash-ai:
	./scripts/bash-ai.sh
inference-tests:
	./scripts/inference-tests.sh
