"""user-post relationship with mappings fix typo for model

Revision ID: 0b470056e9ca
Revises: 4ff72467e25d
Create Date: 2025-01-24 20:43:10.477810

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b470056e9ca'
down_revision: Union[str, None] = '4ff72467e25d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
