"""use timezone

Revision ID: 37e2a9f26779
Revises: 92b8678fbb8f
Create Date: 2025-01-24 18:40:06.417297

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "37e2a9f26779"
down_revision: Union[str, None] = "92b8678fbb8f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("timestamp", sa.DateTime(timezone=True), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("images", "timestamp")
    # ### end Alembic commands ###
