"""user-post relationship

Revision ID: 9bf67912f9c9
Revises: 0fd4da923257
Create Date: 2025-01-24 20:32:35.623292

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9bf67912f9c9"
down_revision: Union[str, None] = "0fd4da923257"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("images", sa.Column("email_of_poster", sa.String(), nullable=True))
    op.add_column("images", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "images", "users", ["user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "images", type_="foreignkey")
    op.drop_column("images", "user_id")
    op.drop_column("images", "email_of_poster")
    # ### end Alembic commands ###
