"""user user junction table

Revision ID: a3db5146c322
Revises: a814805dc71c
Create Date: 2025-01-25 09:07:31.910913

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a3db5146c322"
down_revision: Union[str, None] = "a814805dc71c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "follows",
        sa.Column("follower", sa.Integer(), nullable=False),
        sa.Column("following", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["follower"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["following"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("follower", "following"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("follows")
    # ### end Alembic commands ###
