"""user-post relationship with mappings fix typo

Revision ID: f4f90ed04a89
Revises: fe3f5d3c8968
Create Date: 2025-01-24 20:36:30.859684

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f4f90ed04a89"
down_revision: Union[str, None] = "fe3f5d3c8968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
