"""make field non nullable

Revision ID: d7f40ac9fa32
Revises: e45799a29c7b
Create Date: 2025-01-27 08:27:55.634477

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7f40ac9fa32"
down_revision: Union[str, None] = "e45799a29c7b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image_posts", "email_of_poster", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("image_posts", "email_of_poster", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
