name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Run CI Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Docker Compose
      - name: Set up Docker Compose
        uses: docker/setup-buildx-action@v2

      # Step 3: Start services using Docker Compose
      - name: Start services
        run: docker-compose -f docker-compose.yaml up -d db

      # Step 4: Wait for the database to be ready
      - name: Wait for Postgres
        run: |
          for i in {1..10}; do
            if docker exec $(docker ps -qf "name=db") pg_isready -U image_sharing_user; then
              echo "Postgres is ready"; break
            fi
            echo "Waiting for Postgres..."; sleep 5
          done

      # Step 5: Run database migrations
      - name: Run migrations
        run: ./scripts/migrate-head.sh

      # Step 6: Run tests from Makefile
      - name: Run coverage tests
        run: make coverage-tests

      - name: Run static analysis tests
        run: make static-tests

      - name: Run formatting checks
        run: make format

      # Step 7: Tear down Docker Compose services
      - name: Stop services
        if: always()
        run: docker-compose -f docker-compose.yaml down

